per_listener_settings true

listener 1883
protocol mqtt
allow_anonymous true
log_type all
connection_messages true

listener 8883
protocol mqtt
cafile /mosquitto/certs/ca.pem
certfile /mosquitto/certs/server-fullchain.pem
keyfile /mosquitto/certs/server.key
require_certificate false
allow_anonymous true
log_type all
connection_messages true
