worker_processes 1;
events { worker_connections 128; }
http {
  include       mime.types;
  default_type  application/octet-stream;
  sendfile on;

  server {
    listen 443 ssl;
    ssl_certificate     /certs/cdn.pem;
    ssl_certificate_key /certs/cdn.key;
    server_name _;
    root /certs;

    location /pub/cert/lepro-ca.pem { alias /certs/ca.pem; }
    location /pub/cert/AmazonRootCA13.pem { alias /certs/ca.pem; }
    location /pub/cert/AmazonRootCA1.pem { alias /certs/ca.pem; }
    location /device/cert/ { try_files /client-bundle.pem =404; }
    location = /device/cert/did/debug/ver/1/sign/lepro {
      alias /certs/client-bundle.pem;
    }
    location /healthz {
      return 200 "ok\n";
      add_header Content-Type text/plain;
    }
  }
}
