apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: lepro-debug
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0.20
          args: ["/usr/sbin/mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]
          ports:
            - containerPort: 8883
              name: mqtts
          volumeMounts:
            - name: config
              mountPath: /mosquitto/config
            - name: certs
              mountPath: /mosquitto/certs
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: mosquitto-config
        - name: certs
          secret:
            secretName: lepro-mock-pki
