/*
 * Lepro LP BLE protocol — ESP32 port skeleton.
 * Implement by transliterating ../crypto.py, ../protocol.py, ../session.py.
 */
#pragma once

#include <stdint.h>
#include <stddef.h>

/* Load from lepro_creds.h generated by lepro-bond --export-provision */

int lepro_session_control(const uint8_t *dp_json, size_t dp_len);
